backend:
  name: git-gateway
  branch: main

collections:
  - name: "moves"
    label: "Moves"
    folder: "content/moves"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
